// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface RefltagActionDict<T> extends BaseActionDict<T> {
  Expr?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  fetch?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  content?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  url?: (this: NonterminalNode, arg0: IterationNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  nonWhitespace?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  whitespace?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface RefltagSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
}

export interface RefltagGrammar extends Grammar {
  createSemantics(): RefltagSemantics;
  extendSemantics(superSemantics: RefltagSemantics): RefltagSemantics;
}

declare const grammar: RefltagGrammar;
export default grammar;

