// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface RefltagActionDict<T> extends BaseActionDict<T> {
  test?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface RefltagSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
}

export interface RefltagGrammar extends Grammar {
  createSemantics(): RefltagSemantics;
  extendSemantics(superSemantics: RefltagSemantics): RefltagSemantics;
}

declare const grammar: RefltagGrammar;
export default grammar;

