// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface RefltagActionDict<T> extends BaseActionDict<T> {
  Block?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: NonterminalNode, arg3: IterationNode) => T;
  Root?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  Template?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  templateText?: (this: NonterminalNode, arg0: IterationNode) => T;
  TemplateEscape?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  Quantifier?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode) => T;
  Modes?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode) => T;
  mode?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  Expression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Term_binary?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Term?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Factor_binary?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Factor?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Primary_parenthesized?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Primary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  identifier?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  identifierPart?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  selector?: (this: NonterminalNode, arg0: IterationNode) => T;
  url?: (this: NonterminalNode, arg0: IterationNode) => T;
  literal?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: IterationNode) => T;
  string?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  nonWhitespace?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  whitespace?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface RefltagSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
}

export interface RefltagGrammar extends Grammar {
  createSemantics(): RefltagSemantics;
  extendSemantics(superSemantics: RefltagSemantics): RefltagSemantics;
}

declare const grammar: RefltagGrammar;
export default grammar;

