// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface RefltagActionDict<T> extends BaseActionDict<T> {
  Statement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  keywords?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Definition?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  Expression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Indexing?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  PropertyAccess?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  FunctionCall_parenthesized?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  FunctionCall_freeForm?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  FunctionCall?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Lambda_parenthesized?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: TerminalNode, arg4: NonterminalNode) => T;
  Lambda_freeForm?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Lambda?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Term_binary?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Term?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Factor_binary?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Factor?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Primary_parenthesized?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  Primary?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Object?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  ObjectMapping?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Array?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  identifier?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  keyword?: (this: NonterminalNode, arg0: Node) => T;
  identifierPart?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  literal?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  number?: (this: NonterminalNode, arg0: IterationNode) => T;
  string?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  nonWhitespace?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  whitespace?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface RefltagSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: RefltagActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: RefltagActionDict<T>): this;
}

export interface RefltagGrammar extends Grammar {
  createSemantics(): RefltagSemantics;
  extendSemantics(superSemantics: RefltagSemantics): RefltagSemantics;
}

declare const grammar: RefltagGrammar;
export default grammar;

