name: Build Logseq Plugin Release

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

permissions:
  contents: read # for checkout

jobs:
  build-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # You might need to adjust this value to your own version

      - uses: pnpm/action-setup@v4
        with:
          version: 10.4.1

      - name: Build
        run: |
          pnpm i && pnpm build
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json icon.png ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "tag_name=git tag --sort version:refname | tail -n 1" >> $GITHUB_OUTPUT

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
